# local
local:
  port: 10081
  serverName: 'koa-server-local'
  env:
    DEBUG: true
  feDefine:
    FE_DEFINE_REPLACE: 'xxxooo'

# test
test:
  port: 5001
  serverName: 'koa-server-test'
  env:
    DEBUG: true
  feDefine:
    FE_DEFINE_REPLACE: 'xxxooo'

# prod
prod:
  port: 5001
  serverName: 'koa-server-prod'
  env:
    DEBUG: false
  feDefine:
    FE_DEFINE_REPLACE: 'xxxooo'
